### ISSUE TITLE
Configuration screen options

### ISSUE THREAD

**Issue by willwade** [hosseinamin/audscan#4]
Config options for scanning:

Language:
  - Import file (from dropbox maybe)
  - Paste file. Will need to verify its a proper markdown file though if we do this. Hmm. 

Switch Access:
  - Ignore second hits: Default Off. If on:
    Time to ignore second hits: (So if a key is pressed within n ms it will ignore it): 0.1 ms
    (Useful for someone who has a tremor)
  - Ignore key presses under n ms: Default 0ms. i.e. if a key is pressed for n ms then it will be detected as a keypress. Otherwise ignore it    

  Auto:
    - Loops (int) - How many times will it automatically loop through the list if nothing is selected?
    Timing:
      - Pause on first item time: Default 0 seconds. (The first item in each list requires its own delay often)
      - Auto-scanning time: Default 0.8 seconds
    - Switch Key to move forward: Space or Enter (just choose one)

  Manual:
    - Switch key to move forward: Space or Enter(Same as down arrow right now)
    - Switch key to select: (the opposite of space or enter selected above) (Same as right arrow)
    - Just note to user the other keys that will act as Up/Left for more options (also: Key for config, key for going to home of tree)

Voice:
  Output voice:
  - Synthesised voice:
    - Choose your voice (List)
    - Select rate
  OR - MP3 recordings (select path maybe?)

  Auditory cue:
  - Provide fast cues first (Bool) (Provides a quick run through of the current list first)
  - Synthesised voice:
    - Choose your voice (List)
    - Select rate
    - Select volume
  OR - MP3 recordings (select path maybe?)
  
Interface:
    - Choose colour scheme:
      - High contrast
      - Pale
      - Blues 
    - Choose font: List

**Comment by willwade** [comment]
4-6 hrs

**Comment by hosseinzoda** [comment]
> Paste file. Will need to verify its a proper markdown file though if we do this. Hmm.

I don't think markdown has validation, It's like html almost everything is accepted.

Though we need to sanitize for html tags, mainly for preventing script injection.

**Comment by willwade** [comment]
Yeah - maybe it would be easier to have a markdown editor in the app..

**Comment by willwade** [comment]
Re: Design on this. Config can be accessed by touch - actually initially it wouldn't be keyboard accessible. Config button could be accessible on the UI at all times..

**Comment by hosseinzoda** [comment]
I did add bootstrap to the project. It helps for having good enough UI. I did add a top navbar with one button "Configuration".

**Comment by willwade** [comment]
Marking as done.
